[package]
name = "badgestore-update-badge-action"
version = "0.1.0"
edition = "2021"
rust-version = "1.69"

[dependencies]
reqwest = { version = "0.11.18", features = ["json", "blocking"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.10.5"