name: Test local action
on:
  push:
    branches: [v1]
  pull_request:
    branches: [v1]

jobs:
  example_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change to local action
        run: "sed -i \"s/image: '.*/image: 'Dockerfile'/g\" action.yml"
      - name: Check new yaml
        run: echo $(cat action.yml)
      - id: loc
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.json,*.yaml"
      - uses: ./
        with:
          right-label: ${{ steps.loc.outputs.Total_code }}
          read-write-key: ${{ secrets.ACTION_RW_KEY }}