name: Test local action
on:
  push:
    branches: [v1]
  pull_request:
    branches: [v1]

jobs:
  example_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change to local action
        run: "sed -i \"s/image: '.*/image: 'Dockerfile'/g\" action.yml"
      - name: Check new yaml
        run: echo $(cat action.yml)
      - id: loc
        name: Count lines of code
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.json,*.yaml"
      - uses: ./
        name: Update badge
        id: badge
        with:
          right-label: ${{ steps.loc.outputs.Total_code }}
          read-write-key: ${{ secrets.ACTION_RW_KEY }}
      - name: Verify content changed
        if: steps.badge.outputs.right-label != steps.loc.outputs.Total_code
        run: echo "The output of the badge was not equal to the input ${{ steps.badge.outputs.right-label}} - ${{ steps.loc.outputs.Total_code}}" && exit 1