name: Test remote action
on:
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [v1]
    types:
      - completed

jobs:
  example_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: loc
        uses: Sh1nku/count-loc-action@v1
        with:
          excluded: "*.json,*.yaml"
      - uses: Sh1nku/badgestore-update-badge-action@v1
        with:
          right-label: ${{ steps.loc.outputs.Total_code }}
          read-write-key: ${{ secrets.ACTION_RW_KEY }}